version: "3.7"

services:
  mongoDB:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      PORT: 5000
      URI: mongodb://localhost/rickandmorty-pacosw1
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
