version: "3.3"

services:
  server:
    build: ./
    restart: always
    environment:
      PORT: 4000
      URI: mongodb://mongodb:27017/rickandmorty-pacosw1
      LIMIT_PAGE: 20
    ports:
      - 4000:4000
    depends_on:
      - mongoDB
    networks:
      - back-end

  mongoDB:
    image: mongo:latest
    networks:
      - back-end
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
networks:
  back-end:
